### ISSUE TITLE
Permission denied during installation

### ISSUE THREAD

**Issue by torkelrogstad** [HazCod/enpass-cli#3]
Output of `python -m pip install -r requirements.txt`:

```
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting pysqlcipher3 (from -r requirements.txt (line 2))
  Using cached pysqlcipher3-1.0.2.tar.gz
Collecting argcomplete (from -r requirements.txt (line 3))
  Using cached argcomplete-1.9.2-py2.py3-none-any.whl
Installing collected packages: pysqlcipher3, argcomplete
  Running setup.py install for pysqlcipher3: started
    Running setup.py install for pysqlcipher3: finished with status 'done'
Exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/user/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/user/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/user/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/user/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/argcomplete'
```

BTW, I believe that `sqlcipher-dev` is called `libsqlcipher-dev` on Debian distros, might be worth pointing out in the README.

**Comment by torkelrogstad** [comment]
A few other things that popped up:

I believe you have the syntax to `ln` wrong, shouldn't it be the other way around?
I assume the last `chown` command is supposed to be `chmod`. Is this correct?

I'd be happy to submit a PR, if that's welcome.

Nice tool, I appreciate it!

**Comment by HazCod** [comment]
Hi @torkelrogstad , thanks for the issue!
I must admit I created the README couple of weeks after the real code,  so it was out of my head.
If you want to submit a PR, i'd be happy to merge it.
